"""Detection signals for Provenance Guard.

Milestone 3 implements Signal 1 (the Groq LLM judge). Signals 2 & 3 (stylometry,
lexical AI-tells) and the confidence combiner arrive in Milestone 4.

Every signal returns a dict with an `ai_probability` in [0.0, 1.0]
(0 = reads fully human, 1 = reads fully AI) so they share one scale — see
planning.md §1.
"""
import re
import statistics

from groq import Groq

from config import (
    AI_THRESHOLD,
    GROQ_API_KEY,
    HUMAN_THRESHOLD,
    LLM_MODEL,
    SIGNAL_WEIGHTS,
    VERDICT_AI,
    VERDICT_HUMAN,
    VERDICT_UNCERTAIN,
)

_client = Groq(api_key=GROQ_API_KEY)

# The classifier prompt. The model is judging attribution, not answering the text.
# We ask for a bounded probability + a one-line reason and parse both defensively.
LLM_SYSTEM_PROMPT = """You are an AI-content attribution classifier for a creative \
writing platform. Given a passage of text, judge how likely it is that the text was \
generated by an AI language model rather than written by a human.

Weigh holistic, semantic signals: overly smooth or even coherence, generic hedging \
and boilerplate, absence of lived specificity or genuine personal voice, and \
"safe"/balanced phrasing all point toward AI. Idiosyncrasy, strong opinion, \
unpredictable concrete detail, and irregular voice point toward human.

You are estimating a probability, not delivering a verdict. Be calibrated: reserve \
values above 0.85 for text that is almost certainly AI, and below 0.15 for text \
that is almost certainly human. When genuinely unsure, stay near 0.5.

OUTPUT FORMAT — respond with exactly these two lines and nothing else:
Probability: <a number between 0 and 1, e.g. 0.73>
Reason: <one concise sentence>"""

# Caption-specific prompt for the image_description modality (multi-modal stretch).
# Image captions/alt-text have different AI tells than prose, so the judge is retuned.
CAPTION_SYSTEM_PROMPT = """You are an AI-content attribution classifier for image \
captions and alt-text on a creative platform. Given a short description of an image, \
judge how likely it was generated by an AI rather than written by a human.

AI-generated captions tend to: exhaustively and objectively enumerate everything in \
the scene, use generic aesthetic adjectives ("stunning", "vibrant", "serene"), open \
with framing like "This image shows" / "A photo of", and carry no personal reaction \
or context. Human captions tend to be selective, subjective, emotional, incomplete, \
or reference private context ("finally caught the sunrise after 3 tries").

You are estimating a probability, not delivering a verdict. Reserve values above 0.85 \
for near-certain AI and below 0.15 for near-certain human; when unsure stay near 0.5.

OUTPUT FORMAT — respond with exactly these two lines and nothing else:
Probability: <a number between 0 and 1, e.g. 0.73>
Reason: <one concise sentence>"""


def _clamp01(x: float) -> float:
    return max(0.0, min(1.0, x))


def _parse_probability(raw: str) -> float | None:
    """Pull the float after a 'Probability:' line; return None if absent/unparseable."""
    for line in raw.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("probability:"):
            value = stripped.split(":", 1)[1].strip().rstrip(".")
            try:
                return _clamp01(float(value))
            except ValueError:
                return None
    return None


def _parse_reason(raw: str) -> str:
    for line in raw.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("reason:"):
            return stripped.split(":", 1)[1].strip()
    return "No reason provided by classifier."


def llm_signal(text: str, mode: str = "text") -> dict:
    """Signal 1 — Groq LLM judge (semantic).

    `mode` selects the prompt: "text" for prose, "image_description" for captions
    (multi-modal stretch). Returns {"ai_probability": float in [0,1], "rationale": str}.

    Fails SAFE: on any API error or unparseable response it returns 0.5 — an
    abstention that neither accuses nor clears — so a glitch never produces a
    confident misclassification. See planning.md §1.
    """
    system_prompt = CAPTION_SYSTEM_PROMPT if mode == "image_description" else LLM_SYSTEM_PROMPT
    try:
        completion = _client.chat.completions.create(
            model=LLM_MODEL,
            temperature=0,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Classify this text:\n\n{text}"},
            ],
        )
        raw = completion.choices[0].message.content or ""
    except Exception as exc:  # network/auth/rate errors from Groq
        return {"ai_probability": 0.5,
                "rationale": f"LLM signal unavailable ({type(exc).__name__}); abstaining at 0.5."}

    prob = _parse_probability(raw)
    if prob is None:
        return {"ai_probability": 0.5,
                "rationale": "Could not parse classifier output; abstaining at 0.5."}
    return {"ai_probability": prob, "rationale": _parse_reason(raw)}


# ---------------------------------------------------------------------------
# Signal 2 — Stylometric heuristics (structural). See planning.md §1.
# Each metric maps to an "AI-likeness" in [0,1] via linear interpolation between
# two cutoffs; the three are averaged. Cutoffs are starting values, calibrated
# against the M4 test inputs.
# ---------------------------------------------------------------------------

_WORD_RE = re.compile(r"[A-Za-z']+")
# The 11 punctuation types from planning.md §1 (no plain hyphen — it's too common
# in ordinary prose and would water down the metric's discriminative power).
_PUNCT_TYPES = [".", ",", ";", ":", "—", "(", ")", "!", "?", "…", '"']


def _ramp_down(value: float, one_at: float, zero_at: float) -> float:
    """1.0 at/below `one_at`, 0.0 at/above `zero_at`, linear between (one_at<zero_at)."""
    if value <= one_at:
        return 1.0
    if value >= zero_at:
        return 0.0
    return (zero_at - value) / (zero_at - one_at)


def _sentences(text: str) -> list[str]:
    return [s for s in re.split(r"[.!?]+", text) if s.strip()]


def _words(text: str) -> list[str]:
    return _WORD_RE.findall(text.lower())


def stylometry_signal(text: str) -> dict:
    """Signal 2 — structural regularity. Returns ai_probability + component metrics."""
    words = _words(text)
    sentences = _sentences(text)

    # Sentence-length std-dev (words per sentence). Uniform -> AI-like.
    sent_lengths = [len(_words(s)) for s in sentences] or [len(words)]
    sd = statistics.pstdev(sent_lengths) if len(sent_lengths) > 1 else 0.0
    sd_score = _ramp_down(sd, one_at=3.0, zero_at=12.0)

    # Type-token ratio over first 100 words. Repetitive/low diversity -> AI-like.
    window = words[:100]
    ttr = len(set(window)) / len(window) if window else 0.5
    ttr_score = _ramp_down(ttr, one_at=0.45, zero_at=0.75)

    # Punctuation variety (distinct types). Flat -> AI-like.
    distinct_punct = sum(1 for p in _PUNCT_TYPES if p in text)
    punct_score = _ramp_down(float(distinct_punct), one_at=1.0, zero_at=5.0)

    ai_probability = _clamp01((sd_score + ttr_score + punct_score) / 3.0)
    return {
        "ai_probability": ai_probability,
        "metrics": {
            "sentence_length_sd": round(sd, 2),
            "type_token_ratio": round(ttr, 3),
            "distinct_punctuation": distinct_punct,
        },
    }


# ---------------------------------------------------------------------------
# Signal 3 — Lexical "AI-tell" markers (lexical). See planning.md §1.
# Density of LLM-favored filler/hedging phrases + repeated bigrams. Lowest weight.
# ---------------------------------------------------------------------------

_MARKER_PHRASES = [
    "it is important to note", "it is worth noting", "it's important to note",
    "furthermore", "moreover", "in conclusion", "in summary", "on the other hand",
    "when it comes to", "plays a crucial role", "plays a significant role",
    "a testament to", "in today's", "in the realm of", "the world of", "delve",
    "navigating the", "it is essential", "it is equally", "ensure responsible",
    "paradigm shift", "landscape of", "tapestry", "underscores", "multifaceted",
]


def lexical_signal(text: str) -> dict:
    """Signal 3 — lexical AI-tells. Returns ai_probability + diagnostics."""
    lowered = text.lower()
    words = _words(text)
    n_words = max(1, len(words))

    phrase_hits = sum(lowered.count(p) for p in _MARKER_PHRASES)
    phrases_per_100 = 100.0 * phrase_hits / n_words
    phrase_component = _clamp01(phrases_per_100 / 2.5)  # ~2.5 per 100 words -> saturated

    # Repeated-bigram ratio: how much of the text is bigrams seen more than once.
    bigrams = list(zip(words, words[1:]))
    repeated = 0
    seen: dict = {}
    for bg in bigrams:
        seen[bg] = seen.get(bg, 0) + 1
    repeated = sum(c for c in seen.values() if c > 1)
    rep_ratio = repeated / len(bigrams) if bigrams else 0.0
    rep_component = _clamp01(rep_ratio / 0.15)  # 15% repeated bigrams -> saturated

    ai_probability = _clamp01(0.6 * phrase_component + 0.4 * rep_component)
    return {
        "ai_probability": ai_probability,
        "diagnostics": {
            "marker_phrase_hits": phrase_hits,
            "repeated_bigram_ratio": round(rep_ratio, 3),
        },
    }


# ---------------------------------------------------------------------------
# Confidence combiner. See planning.md §2: weighted vote, asymmetric thresholds,
# unified confidence formula, disagreement guard, and length floor.
# ---------------------------------------------------------------------------

DISAGREEMENT_SPREAD = 0.40
LENGTH_FLOOR_STYLO = 40   # below this, stylometry is dropped (unreliable)
LENGTH_FLOOR_FORCE = 15   # below this, force uncertain (too little signal)


def _verdict_from_probability(p: float) -> str:
    if p >= AI_THRESHOLD:
        return VERDICT_AI
    if p < HUMAN_THRESHOLD:
        return VERDICT_HUMAN
    return VERDICT_UNCERTAIN


def combine(llm: float, stylo: float, lexical: float, word_count: int,
            use_stylometry: bool = True) -> dict:
    """Merge the signal probabilities into one calibrated verdict.

    `use_stylometry=False` (e.g. the image_description modality) runs the vote over
    LLM + lexical only. Returns: ai_probability, verdict, confidence, and diagnostics
    (weights used, signal spread, rule notes) — everything the audit log needs.
    """
    notes = []

    # --- Pick which signals are active and their weights ---
    if not use_stylometry:
        # Image_description modality: stylometry N/A, and lexical AI-tells are
        # prose-oriented (rarely present in captions), so the caption-tuned LLM judge
        # dominates. See planning.md stretch #4.
        active = {"llm": llm, "lexical": lexical}
        weights = {"llm": 0.80, "lexical": 0.20}
        notes.append("image_description modality: stylometry not applicable; LLM-dominant weighting")
    elif word_count < LENGTH_FLOOR_STYLO:
        active = {"llm": llm, "lexical": lexical}
        weights = {"llm": SIGNAL_WEIGHTS["llm"], "lexical": SIGNAL_WEIGHTS["lexical"]}
        notes.append(f"text < {LENGTH_FLOOR_STYLO} words: stylometry dropped, weights renormalized")
    else:
        active = {"llm": llm, "stylometric": stylo, "lexical": lexical}
        weights = dict(SIGNAL_WEIGHTS)

    total_w = sum(weights.values())
    ai_probability = _clamp01(sum(weights[k] * active[k] for k in active) / total_w)

    verdict = _verdict_from_probability(ai_probability)
    confidence = _clamp01(2 * abs(ai_probability - 0.5))

    # --- Disagreement guard: a strong split can REVOKE an AI accusation, never
    # manufacture one. It only downgrades likely_ai -> uncertain (protecting a human
    # from being confidently mislabeled); it never forces a human verdict to uncertain.
    # This asymmetry mirrors the false-positive-averse thresholds. See planning.md §2.
    # Guard is a prose-mode feature (assumes the full set of independent signals);
    # in caption mode the prose-oriented lexical signal would create false disagreement.
    spread = max(active.values()) - min(active.values())
    if use_stylometry and spread > DISAGREEMENT_SPREAD and verdict == VERDICT_AI:
        verdict = VERDICT_UNCERTAIN
        confidence = min(confidence, 0.29)  # forced into the "low" band
        notes.append(f"signals disagree (spread {spread:.2f} > {DISAGREEMENT_SPREAD}): AI verdict revoked -> uncertain")

    # --- Hard floor: too short to judge at all (prose only; captions are expected
    # to be short, and the caption-tuned LLM judge can still assess them) ---
    if use_stylometry and word_count < LENGTH_FLOOR_FORCE:
        verdict = VERDICT_UNCERTAIN
        confidence = min(confidence, 0.15)
        notes.append(f"text < {LENGTH_FLOOR_FORCE} words: forced uncertain")

    return {
        "ai_probability": round(ai_probability, 4),
        "verdict": verdict,
        "confidence": round(confidence, 4),
        "weights_used": weights,
        "signal_spread": round(spread, 4),
        "notes": notes,
    }
