"""Detection signals for Provenance Guard.

Milestone 3 implements Signal 1 (the Groq LLM judge). Signals 2 & 3 (stylometry,
lexical AI-tells) and the confidence combiner arrive in Milestone 4.

Every signal returns a dict with an `ai_probability` in [0.0, 1.0]
(0 = reads fully human, 1 = reads fully AI) so they share one scale — see
planning.md §1.
"""
from groq import Groq

from config import GROQ_API_KEY, LLM_MODEL

_client = Groq(api_key=GROQ_API_KEY)

# The classifier prompt. The model is judging attribution, not answering the text.
# We ask for a bounded probability + a one-line reason and parse both defensively.
LLM_SYSTEM_PROMPT = """You are an AI-content attribution classifier for a creative \
writing platform. Given a passage of text, judge how likely it is that the text was \
generated by an AI language model rather than written by a human.

Weigh holistic, semantic signals: overly smooth or even coherence, generic hedging \
and boilerplate, absence of lived specificity or genuine personal voice, and \
"safe"/balanced phrasing all point toward AI. Idiosyncrasy, strong opinion, \
unpredictable concrete detail, and irregular voice point toward human.

You are estimating a probability, not delivering a verdict. Be calibrated: reserve \
values above 0.85 for text that is almost certainly AI, and below 0.15 for text \
that is almost certainly human. When genuinely unsure, stay near 0.5.

OUTPUT FORMAT — respond with exactly these two lines and nothing else:
Probability: <a number between 0 and 1, e.g. 0.73>
Reason: <one concise sentence>"""


def _clamp01(x: float) -> float:
    return max(0.0, min(1.0, x))


def _parse_probability(raw: str) -> float | None:
    """Pull the float after a 'Probability:' line; return None if absent/unparseable."""
    for line in raw.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("probability:"):
            value = stripped.split(":", 1)[1].strip().rstrip(".")
            try:
                return _clamp01(float(value))
            except ValueError:
                return None
    return None


def _parse_reason(raw: str) -> str:
    for line in raw.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("reason:"):
            return stripped.split(":", 1)[1].strip()
    return "No reason provided by classifier."


def llm_signal(text: str) -> dict:
    """Signal 1 — Groq LLM judge (semantic).

    Returns {"ai_probability": float in [0,1], "rationale": str}.

    Fails SAFE: on any API error or unparseable response it returns 0.5 — an
    abstention that neither accuses nor clears — so a glitch never produces a
    confident misclassification. See planning.md §1.
    """
    try:
        completion = _client.chat.completions.create(
            model=LLM_MODEL,
            temperature=0,
            messages=[
                {"role": "system", "content": LLM_SYSTEM_PROMPT},
                {"role": "user", "content": f"Classify this text:\n\n{text}"},
            ],
        )
        raw = completion.choices[0].message.content or ""
    except Exception as exc:  # network/auth/rate errors from Groq
        return {"ai_probability": 0.5,
                "rationale": f"LLM signal unavailable ({type(exc).__name__}); abstaining at 0.5."}

    prob = _parse_probability(raw)
    if prob is None:
        return {"ai_probability": 0.5,
                "rationale": "Could not parse classifier output; abstaining at 0.5."}
    return {"ai_probability": prob, "rationale": _parse_reason(raw)}
