"""Transparency label generation. See planning.md §2 (confidence bands) and §3
(the three verbatim label variants).

The verdict selects the variant; for the AI and human variants a confidence word
(high / moderate / low) is filled in from the score, so a borderline result reads
"(confidence: moderate)" rather than overstating certainty. The uncertain variant
carries no confidence word — being inconclusive is its whole message.
"""
from config import VERDICT_AI, VERDICT_HUMAN

# Confidence-band cutoffs on the derived confidence = 2*|ai_probability - 0.5|.
BAND_HIGH = 0.60
BAND_MODERATE = 0.30

_AI_LABEL = (
    "🤖 Likely AI-generated. Our detection tools indicate this text was most likely "
    "produced with generative AI (confidence: {level}). This is an automated "
    "estimate, not a definitive judgment. If you wrote this yourself, you can "
    "appeal — see below."
)
_HUMAN_LABEL = (
    "✍️ Likely human-written. Our detection tools found no strong signs of AI "
    "generation in this text (confidence: {level}). No attribution tool is perfect, "
    "but nothing here suggests this wasn't written by a person."
)
_UNCERTAIN_LABEL = (
    "❓ Attribution uncertain. Our tools couldn't confidently tell whether this text "
    "was written by a person or generated by AI. Please treat this as inconclusive — "
    "we deliberately avoid labeling a human's work as AI when the evidence is mixed."
)


def confidence_band(confidence: float) -> str:
    """Map a confidence score to a plain-language band word."""
    if confidence >= BAND_HIGH:
        return "high"
    if confidence >= BAND_MODERATE:
        return "moderate"
    return "low"


def make_label(verdict: str, confidence: float) -> str:
    """Return the reader-facing transparency label for a verdict + confidence."""
    if verdict == VERDICT_AI:
        return _AI_LABEL.format(level=confidence_band(confidence))
    if verdict == VERDICT_HUMAN:
        return _HUMAN_LABEL.format(level=confidence_band(confidence))
    return _UNCERTAIN_LABEL
